version: '3.1'
services:
  cms-web-nginx:
    image: 'nginx:alpine'
    container_name: cms-web-nginx
    working_dir: /var/www
    volumes:
      - ../cake:/var/www
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - '80:80'
    links:
      - cms-php-fpm
      - cms-db-pg
  cms-php-fpm:
    build: ./php-fpm
    container_name: cms-php-fpm
    working_dir: /var/www
    volumes:
      - ../cake:/var/www
      - ./php-fpm/php-ini-overrides.ini:/etc/php/7.4/fpm/conf.d/99-overrides.ini
  cms-db-pg:
    build: ./postgreSQL
    container_name: cms-db-pg
    restart: always
    environment:
      POSTGRES_USER: cms
      POSTGRES_PASSWORD: cms
      POSTGRES_HOST_AUTH_METHOD: trust
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - ./postgreSQL/data:/var/lib/postgresql/data/pgdata
    ports:
      - '5432:5432'